# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_dash_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='postedto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentedto', to='user_dash_app.Posts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='user_dash_app.Users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='postedto',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='postedto', to='user_dash_app.Users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='poster',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='user_dash_app.Users'),
            preserve_default=False,
        ),
    ]
