# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='postedto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postedto', to='user_dash_app.Users'),
        ),
        migrations.AddField(
            model_name='posts',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='user_dash_app.Users'),
        ),
        migrations.AddField(
            model_name='comments',
            name='postedto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentedto', to='user_dash_app.Posts'),
        ),
        migrations.AddField(
            model_name='comments',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='user_dash_app.Users'),
        ),
    ]
